# Eureka Instance Configuration
eureka:
  instance:
    hostname: discovery-server
  # Eureka Client Configuration
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  # Eureka Server Configuration
  server:
    renewal-percent-threshold: 0.50

# Server Port
server:
  port: 8761